#!/usr/bin/env ruby

require 'json'

cwd = File.dirname(__FILE__)
blocks = Dir["#{cwd}/blocks/*.json"].map { |f| JSON.parse File.read(f) }.reduce({}, :merge)
blocks['_organization'] = 'slide.life'
File.write("#{cwd}/blocks.json", blocks.to_json)