#!/usr/bin/env ruby

require 'json'

cwd = File.dirname(__FILE__)
schema = Dir["#{cwd}/blocks/*.json"].map { |f| JSON.parse File.read(f) }.reduce({}, :merge)
block = { :organization => 'slide.life', :schema => schema }
File.write("#{cwd}/blocks.json", block.to_json)